donation_app/main/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required
from flask_login import current_user
from datetime import date, datetime
from donation_app.models import ItemType, User, DonationPlace, DonationItem
from donation_app.main.forms import DonationPlaceForm, DonationItemForm
import os
from werkzeug.utils import secure_filename

from donation_app.extensions import app, db, bcrypt

main = Blueprint("main", __name__)

def decode_itemtype(array_of_items):
    str_array = []
    for item in array_of_items:
        for choice in ItemType.choices():
            if item == choice[0]:
                item_str = str(choice[1])
                # print(item_str)
                str_array.append(item_str)
    return str_array

@main.route('/')
def homepage():
    return render_template('home.html')

###################################
###################################
###       Donation Places       ###
###################################
###################################

@main.route('/donation_places')
def donation_places_index():
    all_places = DonationPlace.query.all()
    return render_template('donation_places.html', all_places=all_places)

@main.route('/view_donation_place/<donation_place_id>')
def donation_place_view(donation_place_id):
    place = DonationPlace.query.filter_by(id=donation_place_id).one()
    items = decode_itemtype(place.item_types)
    # print(place.favorited_by)
    return render_template('view_donation_place.html', place=place, items=items)

@main.route('/new_donation_place', methods=['GET', 'POST'])
def donation_places_new():
    form = DonationPlaceForm()
    if form.validate_on_submit():
        image_dir = os.path.join(
            os.path.dirname(app.instance_path), 'donation_app/static/img'
        )

        files_filenames = []
        for file in form.photos.data:
            file_filename = secure_filename(file.filename)
            file.save(os.path.join(image_dir, file_filename))
            files_filenames.append(file_filename)

        print(files_filenames)

        place = DonationPlace(
            title = form.title.data,
            address = form.address.data,
            item_types = form.item_types.data,
            description = form.description.data,
            date_added = datetime.now(),
            photos = files_filenames
        )
        db.session.add(place)
        db.session.commit()
        return redirect(url_for('main.donation_place_view', donation_place_id=place.id))
    return render_template('create_donation_place.html', form=form)

@main.route('/<donation_place_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_donation_place(donation_place_id):
    place = DonationPlace.query.filter_by(id=donation_place_id).one()
    form = DonationPlaceForm(obj=place)

    if form.validate_on_submit():
        for file in form.photos.data:
            if file.filename:
                image_dir = os.path.join(
                    os.path.dirname(app.instance_path), 'donation_app/static/img'
                )
                print('FILE NOT NULL, UPDATING FILENAME')
                file_filename = secure_filename(file.filename)
                file.save(os.path.join(image_dir, file_filename))
                place.photos.append(file_filename)

        place.title = form.title.data
        place.address = form.address.data
        place.item_types = form.item_types.data
        place.description = form.description.data
        

        place = db.session.merge(place)
        db.session.add(place)
        db.session.commit()

        flash(f'Updated {place.title}')
        return redirect(url_for('main.donation_place_view', donation_place_id=place.id))
    return render_template('edit_donation_place.html', form=form, place=place)

@main.route('/<donation_place_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_donation_place(donation_place_id):
    place = DonationPlace.query.filter_by(id=donation_place_id).one()
    place = db.session.merge(place)
    db.session.delete(place)
    db.session.commit()
    flash(f'Deleted {place.title}')
    # stretch challenge: try to add an undo button??
    return redirect(url_for('main.donation_places_index'))


@main.route('/<place_id>/add_favorite_place', methods=['GET', 'POST'])
@login_required
def add_favorite_place(place_id):
    place = DonationPlace.query.filter_by(id=place_id).one()
    current_user.favorite_places.append(place)
    merged_user = db.session.merge(current_user)
    db.session.add(merged_user)
    db.session.commit()
    flash(f'Added {place.title} to your favorite places')
    return redirect(url_for('main.donation_place_view', donation_place_id=place.id))

###################################
###################################
###  Profiles & Donation Items  ###
###################################
###################################

@main.route('/profile/<username>')
@login_required
def profile(username):
    user = User.query.filter_by(username=username).one()
    return render_template('profile.html', user=user)

@main.route('/items/<username>')
@login_required
def view_items(username):
    user = User.query.filter_by(username=username).one()
    items = DonationItem.query.filter_by(created_by_id=user.id).all()
    return render_template('items.html', user=user, user_items=items)

@main.route('/items/create', methods=['GET', 'POST'])
@login_required
def create_item():
    form = DonationItemForm()
    
    if form.validate_on_submit():
        merged_user = db.session.merge(current_user)

        image_dir = os.path.join(
            os.path.dirname(app.instance_path), 'donation_app/static/img'
        )

        img_file = form.photo.data
        # print(f'PROVIDED FILENAME {img_file.filename}')
        filename = secure_filename(img_file.filename)
        img_file.save(os.path.join(image_dir, filename))

        new_item = DonationItem(
            name = form.name.data,
            description = form.description.data,
            photo = img_file.filename,
            item_type = form.item_type.data,
            date_added = datetime.now(),
            created_by = merged_user
        )
        
        db.session.add(new_item)
        db.session.commit()
        flash('New Item Added')

        return redirect(url_for('main.view_items', username=current_user.username))
    return render_template('create_item.html', form=form)

@main.route('/items/<item_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_item(item_id):
    item = DonationItem.query.filter_by(id=item_id).one()
    form = DonationItemForm(obj=item)

    if form.validate_on_submit():
        # if img_file != None and os.path.isfile(path) == False:
        if form.photo.data.filename:
            print('FILE NOT NULL, UPDATING FILENAME')
            image_dir = os.path.join(
                os.path.dirname(app.instance_path), 'donation_app/static/img'
            )
            img_file = form.photo.data
            # print(f'PROVIDED FILENAME {img_file.filename}')
            filename = secure_filename(img_file.filename)
            img_file.save(os.path.join(image_dir, filename))
            item.photo = img_file.filename

        item.name = form.name.data
        item.description = form.description.data
        item.item_type = form.item_type.data

        item = db.session.merge(item)
        db.session.add(item)
        db.session.commit()

        flash(f'Updated {item.name}')
        return redirect(url_for('main.view_items', username=current_user.username))
    return render_template('edit_item.html', form=form, item=item)

@main.route('/items/<item_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_item(item_id):
    item = DonationItem.query.filter_by(id=item_id).one()
    # print(item)
    item = db.session.merge(item)
    db.session.delete(item)
    db.session.commit()
    flash(f'Deleted {item.name}')
    # stretch challenge: try to add an undo button??
    return redirect(url_for('main.view_items', username=current_user.username))

donation_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/styles.css')}}">
    <link rel="icon" href="{{url_for('static', filename='img/icon.png')}}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    
    {% include 'partials/navbar.html' %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <p class="mt-2">{{ message }}</p>
        {% endfor %}
    </div>

    {% block content %}{% endblock %}
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

donation_app/templates/create_donation_place.html
{% extends 'base.html' %}
{% block title %}Create New Donation Place{% endblock %}
{% block content %}
<div class="container">
    <a href="/donation_places">← Back To Places</a>
    <form method="POST" action="{{ url_for('main.donation_places_new') }}">
        {{ form.csrf_token }}
        <fieldset>
            <legend>Create a New Donation Place</legend>

            {{ form.title.label }}
            {{ form.title }}
            <ul>
            {% for error in form.title.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
            
            {{ form.address.label }}
            {{ form.address }}
            <ul>
            {% for error in form.address.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
            
            {{ form.item_types.label }}
            <p></p>
            {% for subfield in form.item_types %}
                <tr>
                    <td>{{ subfield }}</td>
                    <td>{{ subfield.label }}</td>
                </tr>
            {% endfor %}

            <ul>
            {% for error in form.item_types.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>

            {{ form.description.label }}
            {{ form.description }}
            <ul>
            {% for error in form.description.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
                
            {{ form.submit }}
        </fieldset>
    </form>
</div>
{% endblock %}

donation_app/templates/create_item.html
{% extends 'base.html' %}
{% block title %}Create New Donation Item{% endblock %}
{% block content %}
<div class="container">
    <form method="POST" action="/items/create" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <fieldset>
            <legend>Create a New Donation Item</legend>

            {{ form.name.label }}
            {{ form.name }}
            <ul>
            {% for error in form.name.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
            
            {{ form.description.label }}
            {{ form.description }}
            <ul>
            {% for error in form.description.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>

            {{ form.photo.label }}
            {{ form.photo }}
            <ul>
            {% for error in form.photo.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
            
            {{ form.item_type.label }}
            {{ form.item_type }}

            <ul>
            {% for error in form.item_type.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
                
            <!-- <button type="submit">Submit</button> -->
            {{form.submit}}
        </fieldset>
    </form>
</div>
{% endblock %}

donation_app/templates/donation_places.html
{% extends 'base.html' %}
{% block title %}Donation Places{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="mt-4">All Donation Locations</h2>
        <a href="/new_donation_place" class="btn btn-primary">Add New Donation Place</a>
        <div>
            {%- for row in all_places|batch(3) %}
                <div class="row text-center my-4">
                {%- for place in row %}
                    <div class="col-lg-4">
                        <h6>{{ place.title }}</h6>
                        {{ place.address }}
                        <a href="/view_donation_place/{{ place.id }}">View Place</a>
                    </div>
                {%- endfor %}
                </div>
            {%- endfor %}
        </div>
    </div>
{% endblock %}

donation_app/templates/edit_donation_place.html
{% extends 'base.html' %}
{% block title %}Edit Donation Item{% endblock %}
{% block content %}
<div class="container">
    <a href="/donation_places">← Back To Places</a>
    <form method="POST" action="/{{place.id}}/edit" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <fieldset>
            <legend>Edit {{ place.title }}</legend>

            {{ form.title.label }}
            {{ form.title }}
            <ul>
            {% for error in form.title.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
            
            {{ form.address.label }}
            {{ form.address }}
            <ul>
            {% for error in form.address.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
            
            {{ form.item_types.label }}
            <p></p>
            {% for subfield in form.item_types %}
                <tr>
                    <td>{{ subfield }}</td>
                    <td>{{ subfield.label }}</td>
                </tr>
            {% endfor %}

            <ul>
            {% for error in form.item_types.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>

            {{ form.description.label }}
            {{ form.description }}
            <ul>
            {% for error in form.description.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>

            {{ form.photos.label }}
            {{ form.photos }}
            <ul>
            {% for error in form.photos.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
                
            {{ form.submit }}
        </fieldset>
    </form>
</div>
{% endblock %}

donation_app/templates/edit_item.html
{% extends 'base.html' %}
{% block title %}Edit Donation Item{% endblock %}
{% block content %}
<div class="container">
    <a href="/items/{{current_user.username}}">← Back To Items</a>
    <form method="POST" action="/items/{{ item.id }}/edit" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <fieldset>
            <legend>Edit {{ item.name }}</legend>

            {{ form.name.label }}
            {{ form.name }}
            <ul>
            {% for error in form.name.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
            
            {{ form.description.label }}
            {{ form.description }}
            <ul>
            {% for error in form.description.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>

            {{ form.photo.label }}
            {{ form.photo }}
            <ul>
            {% for error in form.photo.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
            
            {{ form.item_type.label }}
            {{ form.item_type }}

            <ul>
            {% for error in form.item_type.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
                
            <!-- <button type="submit">Submit</button> -->
            {{form.submit}}
        </fieldset>
    </form>
</div>
{% endblock %}

donation_app/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 100px;">
            <div class="col-lg-8 mt-auto">
                <h1 class="mb-3">Charity Finder</h1>
                <p>Lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum</p>
            </div>
            <div class="col-lg-4">
                <img src="{{ url_for('static', filename='img/donation_items.png') }}" alt="">
            </div>
        </div>
        <div class="row justify-content-between text-center">
            <div class="col-md-3" id="home-card">
                <img src="{{ url_for('static', filename='img/home_card_1.png') }}" alt="" class="img-fluid mx-auto d-block my-3">
                <p>Log Items You Want To Donate</p>
            </div>
            <div class="col-md-3 col-offset-1" id="home-card">
                <img src="{{ url_for('static', filename='img/home_card_2.png') }}" alt="" class="img-fluid mx-auto d-block my-3">
                <p>Track Your Favorite Donation Locations</p>
            </div>
            <div class="col-md-3 col-offset-1" id="home-card">
                <img src="{{ url_for('static', filename='img/home_card_3.png') }}" alt="" class="img-fluid mx-auto d-block">
                <p>Match Your Items With Your Locations</p>
            </div>
        </div>
    </div>
{% endblock %}

donation_app/templates/items.html
{% extends 'base.html' %}
{% block title %}{{ user.username }}'s Items{% endblock %}
{% block content %}
<div class="container">
    <a href="/profile/{{user.username}}">← Back To User Profile</a><br>

    {% if user == current_user %}
        <a href="/items/create" class="btn btn-primary mt-4">Add An Item</a>
    {% endif %}
    

    {% if user_items | length > 0 %}
        {% for row in user_items|batch(3) %}
            <div class="row my-4">
                {% for item in row %}
                    <div class="col-lg-4">
                        <img src="{{ url_for('static', filename='img/' + item.photo) }}" alt=""  id="donation_item_img" class="img-fluid">
                        <p style="font-size: 20px;">{{ item.name }}</p>
                        <p>{{ item.description }}</p>
                        <p>Item Type: {{ item.item_type }}</p>
                        <a href="/items/{{ item.id }}/edit" class="btn btn-secondary">Edit</a>
                        <a href="/items/{{ item.id }}/delete" class="btn btn-danger">Delete</a>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    
    {% else %}
        <p>{{ user.username }} has not added any items yet!</p>
        {% if user == current_user %}
            <a href="/items/create">Add Your First Item</a>
        {% endif %}
    {% endif %}

</div>
{% endblock %}

donation_app/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="container text-center">
    <h3 class="mt-4">Login To Your Account</h3>
    <form action="/login" method="POST" class="mt-4">
        {{ form.csrf_token }}
        <fieldset>

            {{ form.username.label }}
            {{ form.username }}
            <ul>
            {% for error in form.username.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>

            {{ form.password.label }}
            {{ form.password }}
            <ul>
            {% for error in form.password.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>

            {{ form.submit }}
        </fieldset>
    </form>
</div>
{% endblock %}

donation_app/templates/profile.html
{% extends 'base.html' %}
{% block title %}{{ user.username }}'s Profile{% endblock %}
{% block content %}
    <div class="container">
        <h1 class="mt-4">{{ user.username }}'s Profile</h1>
        <a href="/items/{{ user.username }}" class="btn btn-primary my-4">View Donation Items</a>

        {% if user.favorite_places | length > 0 %}
            <p>{{ user.username }}'s Favorite Donation Places</p>
            <ul>
                {% for place in user.favorite_places %}
                    <li>
                        <a href="/view_donation_place/{{ place.id }}">{{ place.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>{{ user.username }} has no favorite donation places yet!</p>
            {% if user == current_user %}
                <a href="/donation_places">Find Some New Favorite Places!</a>
            {% endif %} 
        {% endif %}

    </div>
{% endblock %}

donation_app/templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign Up{% endblock %}
{% block content %}
<div class="container text-center">
    <h3 class="mt-4">Sign Up For an Account</h3>
    <form action="/signup" method="POST" class="mt-4">
        {{ form.csrf_token }}
        <fieldset>
            {{ form.username.label }}
            {{ form.username }}
            <ul>
            {% for error in form.username.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
    
            {{ form.password.label }}
            {{ form.password }}
            <ul>
            {% for error in form.password.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
            </ul>
    
            {{ form.submit }}
        </fieldset>
    </form>
</div>
{% endblock %}

donation_app/templates/view_donation_place.html
{% extends 'base.html' %}
{% block title %}{{ place.title }}{% endblock %}
{% block content %}
<div class="container">
    <a href="/donation_places">← Back To Places</a>
    <h2 class="text-center mt-4">{{ place.title }}</h2>

    <div id="carouselExampleControls" class="carousel carousel-dark slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            {% for img in place.photos %}
                {% if loop.index0 == 0 %}
                    <div class="carousel-item active">
                        <img src="{{ url_for('static', filename='img/' + img) }}" alt=""  id="donation_place_img" class="d-block w-100">
                    </div>
                {% else %}
                    <div class="carousel-item">
                        <img src="{{ url_for('static', filename='img/' + img) }}" alt=""  id="donation_place_img" class="d-block w-100">
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    {% if place.description != None %}
        <p class="text-center my-3">{{ place.description }}</p>
    {% endif %}

    <div class="row d-flex justify-content-evenly">
        <div class="col-md-6">
            {% if place.item_types | length > 0 %}
                <p class="text-center">Items Accepted:</p>
                <ul>
                {% for item in items %}
                    <li>{{ item }}</li>
                {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="col-md-6">
            <p class="text-center">Users Who Favorited This Place:</p>
            <ul>
            {% for user in place.favorited_by %}
                <li>
                    <a href="/profile/{{ user.username }}">{{ user.username }}</a>
                </li>
            {% endfor %}
            </ul>
            <div class="text-center">
                {% if current_user.is_authenticated %}
                    {% if current_user not in place.favorited_by %}
                        <a href="/{{place.id}}/add_favorite_place" class="btn btn-primary">Add To Your Favorites</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 mt-4">
            <a href="/{{ place.id }}/edit" class="btn btn-secondary">Edit</a>
            <a href="/{{ place.id }}/delete" class="btn btn-danger">Delete</a>
        </div>
    </div>    
</div>
{% endblock %}